AppEstudiante/config/routes.rb
Rails.application.routes.draw do
  resources :estudiantes
  get "up" => "rails/health#show", as: :rails_health_check
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "estudiantes#index" 
end

AppEstudiante/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

AppEstudiante/app/models/estudiante.rb
class Estudiante < ApplicationRecord
  validates :celular, presence: true
    validates :celular, numericality: { only_integer: true },
    length: {is: 8}
end

AppEstudiante/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

AppEstudiante/app/controllers/estudiantes_controller.rb
class EstudiantesController < ApplicationController
  before_action :set_estudiante, only: [:show, :edit, :update, :destroy]

  # GET /estudiantes
  # GET /estudiantes.json
  def index
    @estudiantes = Estudiante.all
  end

  # GET /estudiantes/1
  # GET /estudiantes/1.json
  def show
  end

  # GET /estudiantes/new
  def new
    @estudiante = Estudiante.new
  end

  # GET /estudiantes/1/edit
  def edit
  end

  # POST /estudiantes
  # POST /estudiantes.json
  def create
    @estudiante = Estudiante.new(estudiante_params)

    respond_to do |format|
      if @estudiante.save
        format.html { redirect_to @estudiante, notice: 'Estudiante was successfully created.' }
        format.json { render :show, status: :created, location: @estudiante }
      else
        format.html { render :new }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estudiantes/1
  # PATCH/PUT /estudiantes/1.json
  def update
    respond_to do |format|
      if @estudiante.update(estudiante_params)
        format.html { redirect_to @estudiante, notice: 'Estudiante was successfully updated.' }
        format.json { render :show, status: :ok, location: @estudiante }
      else
        format.html { render :edit }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estudiantes/1
  # DELETE /estudiantes/1.json
  def destroy
    @estudiante.destroy
    respond_to do |format|
      format.html { redirect_to estudiantes_url, notice: 'Estudiante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estudiante
      @estudiante = Estudiante.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def estudiante_params
      params.require(:estudiante).permit(:nombre, :apellido, :carrera, :carnet, :nacimiento, :celular)
    end
end

AppEstudiante/app/helpers/application_helper.rb
module ApplicationHelper
end

AppEstudiante/app/helpers/estudiantes_helper.rb
module EstudiantesHelper
end

AppEstudiante/app/views/estudiantes/_form.html.erb
<%= form_with(model: estudiante) do |form| %>
  <% if estudiante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estudiante.errors.count, "error") %> prohibited this estudiante from being saved:</h2>

      <ul>
        <% estudiante.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :apellido %>
    <%= form.text_field :apellido %>
  </div>

  <div class="field">
    <%= form.label :carrera %>
    <%= form.text_area :carrera %>
  </div>

  <div class="field">
    <%= form.label :carnet %>
    <%= form.text_field :carnet %>
  </div>

  <div class="field">
    <%= form.label :nacimiento %>
    <%= form.date_select :nacimiento %>
  </div>

  <div class="field">
    <%= form.label :celular %>
    <%= form.number_field :celular %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

AppEstudiante/app/views/estudiantes/edit.html.erb
<h1>Editing Estudiante</h1>

<%= render 'form', estudiante: @estudiante %>

<%= link_to 'Show', @estudiante %> |
<%= link_to 'Back', estudiantes_path %>

AppEstudiante/app/views/estudiantes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estudiantes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Carrera</th>
      <th>Carnet</th>
      <th>Nacimiento</th>
      <th>Celular</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estudiantes.each do |estudiante| %>
      <tr>
        <td><%= estudiante.nombre %></td>
        <td><%= estudiante.apellido %></td>
        <td><%= estudiante.carrera %></td>
        <td><%= estudiante.carnet %></td>
        <td><%= estudiante.nacimiento %></td>
        <td><%= estudiante.celular %></td>
        <td><%= link_to 'Show', estudiante %></td>
        <td><%= link_to 'Edit', edit_estudiante_path(estudiante) %></td>
        <td><%= link_to 'Destroy', estudiante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estudiante', new_estudiante_path %>

AppEstudiante/app/views/estudiantes/new.html.erb
<h1>New Estudiante</h1>

<%= render 'form', estudiante: @estudiante %>

<%= link_to 'Back', estudiantes_path %>

AppEstudiante/app/views/estudiantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @estudiante.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @estudiante.apellido %>
</p>

<p>
  <strong>Carrera:</strong>
  <%= @estudiante.carrera %>
</p>

<p>
  <strong>Carnet:</strong>
  <%= @estudiante.carnet %>
</p>

<p>
  <strong>Nacimiento:</strong>
  <%= @estudiante.nacimiento %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @estudiante.celular %>
</p>

<%= link_to 'Edit', edit_estudiante_path(@estudiante) %> |
<%= link_to 'Back', estudiantes_path %>

AppEstudiante/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppEstudiante</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>